# Generated by Django 3.0.4 on 2020-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('size', models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('friendliness', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], unique=True)),
                ('trainability', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], unique=True)),
                ('sheddingamount', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], unique=True)),
                ('exerciseneeds', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('color', models.CharField(max_length=200)),
                ('favoritefood', models.CharField(max_length=200)),
                ('favoritetoy', models.CharField(max_length=200)),
            ],
        ),
    ]
